### ISSUE TITLE
Consider using https://github.com/google/go-cmp instead of reflect.DeepEqual

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#138]
DeepEqual isn't always able to compare complex data types.
`resource.Quantity` and `time.Time` for example.

See:
 * https://github.com/google/go-cmp

**Comment by sebbonnet** [comment]
Since I've used `go-cmp` as part of #137 when comparing the pod.Spec, I think the only other occurrence where this might be useful is here: https://github.com/sky-uk/cassandra-operator/blob/v0.70.1-alpha.3/cassandra-operator/pkg/operator/operator.go#L243

I think this is a nice to have though, as we have no `time.Time` or `resource.Quantity` that live outside the `Pod` spec which we already compare correctly. Having the top level struct compared with `go-cmp` would allow to close the gap and ensure any future properties added outside of `Pod` spec will be compared correctly.
