### ISSUE TITLE
Intermittent licence-compliance-checker failures

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#151]
```
cassandra-operator/cassandra-sidecar $ make build
...
ERRO[0005] Some licences are not compliant and/or cannot be identified: restricted: [{/home/richard/go/pkg/mod/github.com/hashicorp/hcl@v1.0.0 [{MPL-2.0-no-copyleft-exception 0.9874513} {MPL-2.0 0.9874513}] }], unidentifiable: [] 
make: *** [Makefile:50: validate-licences] Error 1
```

I don't understand why this isn't occurring on travis.
And it occurs intermittently on my laptop.

The licence checker prints two possible licenses, with equal probabilities:
`[{MPL-2.0-no-copyleft-exception 0.9874513} {MPL-2.0 0.9874513}] `

Perhaps the license matching code is non-deterministic.

**Comment by sebbonnet** [comment]
> Perhaps the license matching code is non-deterministic.

True. I think that might actually be a bug in SPDX database as both MPL 2.0 and MPL 2.0 no copy licences text are the same. I raised this for it, as unsure if this is intentional behaviour: https://github.com/spdx/LicenseListPublisher/issues/55

I also raised https://github.com/sky-uk/licence-compliance-checker/issues/20 to make our licence check more deterministic - fixed is in https://github.com/sky-uk/licence-compliance-checker/pull/21
