### ISSUE TITLE
Cassandra Resource Validation Metrics

### ISSUE THREAD

**Issue by chuckydev** [sky-uk/cassandra-operator#229]
## Motivation
When an invalid change is made to the cassandra resource there is currently no visibility as to whether the change has successfully passed validation or not. 

This can be alerted on in the case that someone was expecting a change to their cluster but it was not applied. I.e. If a PVC increase was attempted but it is not currently supported so it fails validation.

## Requirements
- Per Cluster metric stating whether a resource has succeeded or failed.

### Additional context
- The reconciler metrics are currently not sufficient as the validation simply logs an error to events and passes nil to the reconciler. Otherwise we could have used the reconciler metrics on port 8080. If the reconciler fails we have the `controller_runtime_reconcile_errors_total` which is not cluster specific.

---- To be filled in by Assignee -----
## Tasks/Feature Set
List tasks/features in order to meet the requirements listed above

**Comment by Bez625** [comment]
Discussion is here https://sky.slack.com/archives/CB41RC81H/p1603199364047900

**Comment by Bez625** [comment]
When a Cassandra Resource is validated the spec is examined and validations errors are collected. If one or more validation errors are detected we record an InvalidChange event with the "Message" being aggregated errors as a string.

In order to provide a metric around this - considering the reported case of a PVC change not being supported - we have a few options:

#### 1. We simply increase a failed validation count for the specific Cassandra cluster and namespace:
```
# HELP cassandra_failed_validation_count Total number of failed validations in a Cassandra cluster
# TYPE cassandra_failed_validation_count count
cassandra_failed_validation_count{cluster="some-cassandra",namespace="some-namespace"} 1
```
**PROS:** This is a simple change and covers all validation failures.
**CONS:** It does not help identify why the validation failed. That would require analysis from the user.

#### 2. We only increase metrics for validation failures we are specifically prepared to handle:
```
# HELP cassandra_failed_validation_count Total number of failed validations in a Cassandra cluster
# TYPE cassandra_failed_validation_count count
cassandra_failed_validation_count{cluster="some-cassandra",namespace="some-namespace",reason="PVC_update"} 1
```
**PROS:** The metrics are more informative and allow for the ingester to have better control over their use.
**CONS:** Requires specific development each time a new reason is handled. If there are multiple failures we have to increment multiple metrics and this could lead to multiple alerts for the same validation failure. This does not report unhandled validation failures.

#### 3. Increase metrics for specific handled validation failures and have a catch all for unhandled validation failures.
```
# HELP cassandra_failed_validation_count Total number of failed validations in a Cassandra cluster
# TYPE cassandra_failed_validation_count count
cassandra_failed_validation_count{cluster="some-cassandra",namespace="some-namespace",reason="PVC_update"} 1
cassandra_failed_validation_count{cluster="some-cassandra",namespace="some-namespace",reason="Unspecified"} 1
```
**PROS:** The metrics are more informative, provided that case is handled, and allow for the ingester to have better control over their use.
**CONS:** If there are multiple failures we have to increment multiple metrics and this could lead to multiple alerts for the same validation failure. The logic is a little complicated, e.g. what would we do if there are 3 unhandled failures and 2 handled failures? Is this 5 metric increments or 3?

We should also consider whether a counter is the correct prometheus type for this case.

**Comment by Bez625** [comment]
After discussion we decided to go with option 1 above with a counter and metric name `cassandra_failed_validation_count`
