### ISSUE TITLE
The CI system is slow to report static check errors (go fmt, go vet, etc)

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#66]
In https://github.com/sky-uk/cassandra-operator/pull/61, for example, I missed some documentation for some new public functions, but it took > 20 minutes for this to be reported because the E2E tests had to run first.

Additionally, it's not clear which `make` target i can use locally to run these static checks before committing and pushin.

For a start I propose:
 * [x]  `make verify-all` which I can use to  run these fast checks locally (fmt vet lint validate-licences) (https://github.com/sky-uk/cassandra-operator/pull/68)
*  [ ] Add a Travis build stage called (check) to with a job called `verify` to run these fast checks before the e2e: https://docs.travis-ci.com/user/build-stages/ . 
* [ ] And another job called `test` in the `check` stage which builds the binaries and then runs the tests.

**Comment by sebbonnet** [comment]
I like the idea of splitting up the build so we get an earlier feedback for the static checks.
We would also need to split up the dind cluster creation from the setup as this takes ~10mins.

Given that jobs within a stage run in parallel, I think we need multiple stages rather than multiple jobs. Perhaps `check-style` to run the static checks and `check` where we would create the dind cluster before running the test.
