### ISSUE TITLE
Set OwnerReferences on resources created for a cluster

### ISSUE THREAD

**Issue by kragniz** [sky-uk/cassandra-operator#96]
We should set `metadata.ownerReferences` to point at the owning `Cassandra` object. This allows kubernetes to perform garbage collection when the `Cassandra` is deleted.

See https://github.com/kubernetes/community/blob/548eb7292d45a4af78e0141d33094130dfe6080a/contributors/design-proposals/garbage-collection.md and 
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

**Comment by alangibson01** [comment]
This would be great. We just need to make sure that persistent volumes used by the cluster aren't deleted when the `Cassandra` object is deleted. We want deletion of the data volumes to be an explicit action, so that the state of the cluster could be easily restored in the event that the `Cassandra` was accidentally deleted for some reason.
